### PR TITLE
http_build_query: Use RFC 3986 instead of RFC 1738 to improve interoperability with other libraries (fixes #74)

### LINKED ISSUE #74: New Symfony HTTP client transport not always reliable
At least in the integration test a checksum error occurs some times. See https://github.com/littleredbutton/bigbluebutton-api-php/pull/67#issuecomment-847315036 for details,

### PR DESCRIPTION
**Pull request by FelixJacobi**
First seen on interacting with Symfony HTTP client.

### CODE REVIEW

**Review by SamuelWei — APPROVED** [review]

**Comment by SamuelWei** [comment]
What about `$queries['configXML'] = urlencode($this->rawXml->asXML());` src/Parameters/SetConfigXMLParameters.php

**Comment by FelixJacobi** [comment]
> What about $queries['configXML'] = urlencode($this->rawXml->asXML()); in src/Parameters/SetConfigXMLParameters.php ?

Hm, interesting. I am not familiar with the `configXML` stuff as it was only relevant for the Flash AFAIC client which I never worked with. But I guess its fine to change it too although `http_build_query` already should do the job in theory.

**Comment by FelixJacobi** [comment]
> What about `$queries['configXML'] = urlencode($this->rawXml->asXML());` in src/Parameters/SetConfigXMLParameters.php ?
> I'm not to worried about it, as (see #73) in BBB 2.3 the whole configXML API endpoints are removed
> 
> There are also a few urlencodes in tests/unit/Parameters/CreateMeetingParametersTest.php, it wouldn't make a difference there, but it could be done for conistency

Addressed.

**Comment by SamuelWei** [comment]
> > What about `$queries['configXML'] = urlencode($this->rawXml->asXML());` in src/Parameters/SetConfigXMLParameters.php ?
> > I'm not to worried about it, as (see #73) in BBB 2.3 the whole configXML API endpoints are removed
> > There are also a few urlencodes in tests/unit/Parameters/CreateMeetingParametersTest.php, it wouldn't make a difference there, but it could be done for conistency
> 
> Addressed.

Do you also change it in CreateMeetingParametersTest.php or should we merge?

**Comment by FelixJacobi** [comment]
> > > What about `$queries['configXML'] = urlencode($this->rawXml->asXML());` in src/Parameters/SetConfigXMLParameters.php ?
> > > I'm not to worried about it, as (see #73) in BBB 2.3 the whole configXML API endpoints are removed
> > > There are also a few urlencodes in tests/unit/Parameters/CreateMeetingParametersTest.php, it wouldn't make a difference there, but it could be done for conistency
> > 
> > 
> > Addressed.
> 
> Do you also change it in CreateMeetingParametersTest.php or should we merge?

My fault, forget to include the changes in the commit 😄 . Just a second...

**Comment by FelixJacobi** [comment]
> > > > What about `$queries['configXML'] = urlencode($this->rawXml->asXML());` in src/Parameters/SetConfigXMLParameters.php ?
> > > > I'm not to worried about it, as (see #73) in BBB 2.3 the whole configXML API endpoints are removed
> > > > There are also a few urlencodes in tests/unit/Parameters/CreateMeetingParametersTest.php, it wouldn't make a difference there, but it could be done for conistency
> > > 
> > > 
> > > Addressed.
> > 
> > 
> > Do you also change it in CreateMeetingParametersTest.php or should we merge?
> 
> My fault, forgot to include the changes in the commit smile . Just a second...

Check.

**Pull request merged**
