### PR TITLE
Fix error handling

### LINKED ISSUE #33: Parse only 200 responses
If the BBB api produces an 500 error, it doesn't response with valid XML. So in my opinion we should handle the response code in some way. Does someone know how BBB is using them?

### PR DESCRIPTION
**Pull request by sualko**
@botris I updated your pull request a bit. What do you think?

This way people can check with `$exception instanceof BaseException` if this exception is from our api or something different.

fix #33

### CODE REVIEW

**Comment by SamuelWei** [comment]
I also had a problem with presentations, in case the filename used chars other than A-Za-z0-9.-_\
We could also test exactly what chars are allowed and throw an exception, even before sending data to the server

**Comment by botris** [comment]
The filename check makes sense, but maybe move that to a different issue? I'd personally try not fit all the error handling in one PR, as per the original issue #33 "Parse only 200 responses", the current state of the PR does that well.

**Comment by sualko** [comment]
> I also had a problem with presentations these days, in case the filename used chars other than A-Za-z0-9.-_

Oh boy. Nice catch. BBB is annoying...

> We could also test exactly what chars are allowed and throw an exception

I think this is a bad idea, because this could change on every release. In my opinion this should be handled by server api and result in a proper error response.

**Comment by joisarjignesh** [comment]
@sualko  i m ok with base exception handling . i did not test .
@SamuelWei  nice catching a bigbluebutton presentations filename bug

**Comment by joisarjignesh** [comment]
@SamuelWei 

> I also had a problem with presentations these days, in case the filename used chars other than A-Za-z0-9.-_
> We could also test exactly what chars are allowed and throw an exception, even before sending data to the server

@SamuelWei i try to test which character is allowed or which not
when i try to pass this type of file name : **php_tutorial asdff @  # ^ * $$ ! ` ~ - ) ( + - +  > < .' ; , = d $ %.pdf**
it working properly

but when i try to this file name : **php_tutorial asdff @  # ^ * $$ ! ` ~ - ) ( + - + / > < .' / \; , = d $ %.pdf**
in meeting filename showing as  **; , = d $ %.pdf**

also pass : **php/.pdf** showing as **.pdf**    working
also pass : **php\.pdf** showing as **.pdf**    working
also pass : **.pdf** showing as **.pdf**           working


`$fileName = "php_tutorial asdff sdlkfsdfsdf ksdjflsdfjas fkljsflsakdjflskdjfsd fkjasfkjsf sdkf fasd flsdkfj sflksd falsf skfjasdf ajslfkd flkf lf dlfkjasdlf sdfkasdjf alsdkjfa sfklkasdjf alskjfsdkjasdlf asdlfkas dlkasdjflsa dkfjsldkfjasl fkjadlfkjadf alksdjfaldkjfals fasdkfjds;l fjasldkfjsd fkajsdlf sdlfjasd flaskdjfalkdf alsdkfjasdkfjasd ;fkajsdlffa sdflkajsd faksdjfas ldkfjalsdkfjldsfjldwelkfjw dlkjasdff slfjad jadlkfjadlfjd;lkfja dfkldf dlksf alkfjsdlk fadslkjffa skfjads;lk  @  # ^ * $$ ! ` ~ - ) ( + - +  > < .' ; , = d $ %.pdf";

filename length is 523 character still it working properly 

`but when try pass like that not working
pass **.**(only dot)  not working
pass **.t**(dot with one character) not working

bigbluebutton can not allowing forward slash(/) and backward slash(\) in file  name..
if pass then it will split with last matching slash .

**Comment by SamuelWei** [comment]
@joisarjignesh Could you try some special chars like äüö

**Comment by joisarjignesh** [comment]
@SamuelWei  i try to check special chars like  äüö

it will throw a
**HTTP Status 500 – Internal Server Error**

**Comment by sualko** [comment]
@SamuelWei @joisarjignesh can one of you approve this pr, or is there anything else to do?

**Comment by sualko** [comment]
Regarding the filename: A user has mentioned in the upstream repo, that the content length is probably not correct calculated. Can someone look into this? https://github.com/bigbluebutton/bigbluebutton-api-php/issues/118

**Comment by SamuelWei** [comment]
> Regarding the filename: A user has mentioned in the upstream repo, that the content length is probably not correct calculated. Can someone look into this? [bigbluebutton#118](https://github.com/bigbluebutton/bigbluebutton-api-php/issues/118)


I did some tests to understand BBB's behavoir.
Sending a wrong content-length header results in a 400 error, the same error as with special chars.
In BBB's source code I can't find a validation of the content-length. As far I can tell, it is caused by the nginx webserver, that is validating the header if present. 

The Hypertext Transfer Protocol -- HTTP/1.1 specifies that the content-length should be a decimal number of octes (8-bit sequence = 1 byte). 

> 14.13 Content-Length
> 
>    The Content-Length entity-header field indicates the size of the
>    entity-body, in decimal number of OCTETs, sent to the recipient or,
>    in the case of the HEAD method, the size of the entity-body that
>    would have been sent had the request been a GET.

> 2.2 Basic Rules
> 
>    The following rules are used throughout this specification to
>    describe basic parsing constructs. The US-ASCII coded character set
>    is defined by ANSI X3.4-1986 [21].
> 
>        OCTET          = <any 8-bit sequence of data>

https://www.ietf.org/rfc/rfc2616.txt


The problem with mb_strlen is, that it counts the characters of string, not bytes. As HTTP wants to have the length of bytes not chars, on a missmatch an the error is thrown. We should therefore change mb_strlen() -> strlen()

> strlen() returns the number of bytes rather than the number of characters in a string.
https://www.php.net/manual/en/function.strlen.php

**Review by joisarjignesh — COMMENTED** [review]
today i will test Exception then i give you review

**Comment by sualko** [comment]
> today i will test Exception then i give you review

@joisarjignesh did you find time to test this pr?

**Comment by joisarjignesh** [comment]
@sualko  i test that it's working

**Review by SamuelWei — APPROVED** [review]

**Comment by SamuelWei** [comment]
@sualko What is the status? Can we merge and release?

**Pull request merged**
