### PR TITLE
fix creation time type

### PR DESCRIPTION
**Pull request by sualko**
fix bigbluebutton/bigbluebutton-api-php#85

### CODE REVIEW

**Comment by sualko** [comment]
I think @SamuelWei is right, because bbb is using microseconds.

**Comment by SamuelWei** [comment]
Yes, bbb is using milliseconds (see https://mconf.github.io/api-mate/)
If you want to use unix timestamps (10 digits), we would have to divide by 1000 and save as int

**Comment by GhaziTriki** [comment]
The time is in milliseconds as @SamuelWei did mention. I think double/float should be the right type.

**Comment by SamuelWei** [comment]
What about adding a parameter to choose the high or low precision?

**Comment by sualko** [comment]
What's the advantage and should this be part of an api?

**Comment by SamuelWei** [comment]
The advantage would be that you could use the result directly in other php functions like `date` without additional code. That would make writing code with this api more DRY. It was just an idea, while being confronted by this issue today.

**Comment by sualko** [comment]
> The advantage would be that you could use the result directly in other php functions like date without additional code

Sounds reasonable for me.

**Comment by sualko** [comment]
Can you make another pr?

**Pull request merged**
