### PR TITLE
Remove deprecations

### PR DESCRIPTION
**Pull request by SamuelWei**
- [x] Waiting for #174 
- [x] Waiting for #181 (to remove the newly added deprecation)

### CODE REVIEW

**Review by FelixJacobi — APPROVED** [review]
Nice. But our old friend Coveralls seems to be unhappy, since we removed a lot of previously covered code 😄  .

If we can re-add some coverage with low efforts, I would do that. Otherwise, we can merge with administrative override, I think.

**Comment by SamuelWei** [comment]
Ok, I'll add some tests

**Comment by SamuelWei** [comment]
> Ok, I'll add some tests

@FelixJacobi It took a lot longer than I thought it would, but with #182 and the associated PRs we should have a few more breaking changes before 6.0, as well as increased coverage.

**Comment by FelixJacobi** [comment]
@SamuelWei Can I assist you in some way? Or do you waiting to have some time again? (no pressure ^^ )

**Comment by SamuelWei** [comment]
@FelixJacobi I'll work on it asap, but i'm on vacation the next week. Could you work on other issue for the 6.0 milestone?

**Comment by FelixJacobi** [comment]
Enjoy your vacation, for sure 🙂 . And: Yes, I am going to, there are enough eggs hard to peel.

**Pull request merged**
