### PR TITLE
added release action workflow

### PR DESCRIPTION
**Pull request by jibon57**
This will add ready to use library with every release. This will trigger when you will publish new release.

### CODE REVIEW

**Comment by sualko** [comment]
Thanks for your contribution.

Since this library does not have any dependencies (except some external once), what is the point of building a release like that?

In the past we just created a release here on Github which gets automatically pushed to packagist, which worked fine. This process could maybe optimized via a `.gitattributes` file to exclude e.g. the `.github` folder. I will open a pr for that.

**Comment by jibon57** [comment]
@sualko thanks for reply. This is ready to use library with auto loader included. User can just download & start using. No need to run any command or need composer. This PR was supporting for my blog post [
Connect with BigBlueButton in easy 2 steps using PHP
](https://www.mynaparrot.com/en/blog/179-connect-with-bigbluebutton-in-easy-2-steps-using-php)

**Comment by sualko** [comment]
Thanks for your explanation. For me it's a nice addition. Other thoughts?

**Comment by FelixJacobi** [comment]
For me, it's fine to support such a thing.

Although I see only a few special use cases. Normally, you should use Composer e.g. to get updates of our dependencies as soon as possible. If you would use the zip ball, you won't get any updates of them for e.g. nearly six months if we don't create new releases.

For simply testing out the library, it is a good approach but I wouldn't recommend this for production usage for the reasons described. If we can add a clarification somewhere, I am fine with accepting that here.

**Comment by FelixJacobi** [comment]
Closed due to missing recent activity. Feel free to reopen or submit a new PR.

**Pull request closed without merging**
