### PR TITLE
Make master become 5.0

### PR DESCRIPTION
**Pull request by FelixJacobi**
This merges the removal of all deprecations, removing unsupported PHP versions and BC breaks back to master.

**Note:** Must not be squashed on merge.

### CODE REVIEW

**Comment by FelixJacobi** [comment]
@sualko Could you disable the requirement of PHP 7.2 and 7.3 to pass? 😄

**Comment by SamuelWei** [comment]
> @sualko Could you disable the requirement of PHP 7.2 and 7.3 to pass? 😄

Fixed

**Comment by SamuelWei** [comment]
It was hidden in the protected branches setting

**Comment by SamuelWei** [comment]
@FelixJacobi Is it ready for review?

**Comment by FelixJacobi** [comment]
> @FelixJacobi Is it ready for review?

Yes.

**Comment by SamuelWei** [comment]
Great, looking forward to 5.0 and 5.1, espacilly password deprecation.
I'll do a review this arvo

**Review by SamuelWei — COMMENTED** [review]
What about the deprecated consts in CreateMeetingParameters?

**Review by SamuelWei — APPROVED** [review]
LGTM, Integration tests are also working fine

**Comment by SamuelWei** [comment]
> @FelixJacobi What about the deprecated consts in CreateMeetingParameters?

@FelixJacobi See https://github.com/littleredbutton/bigbluebutton-api-php/blob/62dcbe1dde719733fb7325de7c91bfe84871e416/src/Parameters/CreateMeetingParameters.php#L130 and the following lines
Appart from that this PR can be merged

**Comment by FelixJacobi** [comment]
Yes, I am aware of it, but was quite busy the last days ^^ .

**Comment by FelixJacobi** [comment]
> @FelixJacobi What about the deprecated consts in CreateMeetingParameters?

@SamuelWei Fixed.

**Comment by SamuelWei** [comment]
@FelixJacobi @sualko Should be do a 5.0 release before merging as planed in: https://github.com/littleredbutton/bigbluebutton-api-php/issues/137 ?

**Comment by SamuelWei** [comment]
@FelixJacobi Shouldn't we resolve #120 first?

**Comment by FelixJacobi** [comment]
> @FelixJacobi Shouldn't we resolve #120 first?

Yes, it's planned to do that after that PR separately as this will change a lot of lines in the whole codebase.

**Comment by FelixJacobi** [comment]
> @FelixJacobi @sualko Should be do a 5.0 release before merging as planed in: https://github.com/littleredbutton/bigbluebutton-api-php/issues/137 ?

Not needed. The checklist there is not strictly chronically. For 4.3, we already have a 4.3 branch.

**Comment by SamuelWei** [comment]
> > @FelixJacobi @sualko Should be do a 5.0 release before merging as planed in: #137 ?
> 
> Not needed. The checklist there is not strictly chronically. For 4.3, we already have a 4.3 branch.

ok

**Pull request merged**
