### PR TITLE
Change to GitHub actions

### PR DESCRIPTION
**Pull request by SamuelWei**
Move ci from travis-ci.org to github actions due to shutdown of travis-ci.org.
With travis-ci.com open-source usage is more restricted and an application is required: https://blog.travis-ci.com/oss-announcement

Github actions doesn't have the great 'allow-failure' from travis-ci. To make the ci pass for the allowed failures I added continue-on-error, but it makes the tests look like they all passed.  See: https://github.com/actions/toolkit/issues/399

### CODE REVIEW

**Comment by sualko** [comment]
Can we remove travis?

**Comment by sualko** [comment]
Sorry, was just irritated, that travis still tries to run on this branch.

**Review by sualko — APPROVED** [review]
Looks awesome. I think I will switch to github actions for all of my projects.

**Comment by joisarjignesh** [comment]
good work @SamuelWei

**Pull request merged**
