### PR TITLE
Sync upstream again

### PR DESCRIPTION
**Pull request by FelixJacobi**

### CODE REVIEW

**Comment by SamuelWei** [comment]
If you compare this PR to the original PR there are some differences. See your own review of the original https://github.com/littleredbutton/bigbluebutton-api-php/pull/126/commits/7d440d6b4d8996b72947b36fd6b250fd223309a2

**Comment by FelixJacobi** [comment]
Thanks for the spot. You are right. The reason was that I manually needed to reconstruct the branch (GitHub seems to delete no longer referenced commits quickly, so you can't them even after a `git fetch` :/ ) from an outdated copy that was left had locally on my machine and I missed re-applying this.

I will create a regular PR as a fixup as this is only a cosmetic thing ^^ .

**Comment by SamuelWei** [comment]
Wouldn't it have been possible to restore the old branch and just merge again without stashing? Also instead of the rollback just reset the master to before the merge and force push?

**Comment by FelixJacobi** [comment]
Ah, yes. You are right. The button was quite hidden in the history of the original PR (next to the *deleted branch* message). See #141 for the rest of the changes.

**Pull request merged**
