### PR TITLE
set as protected instead of private so i can used in my package for overwrite object 

### PR DESCRIPTION
**Pull request by joisarjignesh**
set as protected instead of private so i can used in my package for overwrite object

### CODE REVIEW

**Comment by joisarjignesh** [comment]
@SamuelWei and @sualko please approve my request so I can integrate into my pacakge.

**Comment by SamuelWei** [comment]
Hi @joisarjignesh,

you can just use the constructor to set $transport to a custom implementation. Isn't that solving your issue?

Greetings,
Samuel

**Review by sualko — APPROVED** [review]
Since all other properties are also protected, I think it's ok to use it for the transport too. It's probably useful if you like to extend the calss.

**Review by SamuelWei — APPROVED** [review]

**Comment by joisarjignesh** [comment]
@SamuelWei  and @sualko thanks for merging this pull request

**Pull request merged**
