### PR TITLE
Fixed cookie extraction in CurlTransport in PHP 8 (fixes #76)

### LINKED ISSUE #76: CurlTransportTest::testRequestWithCookie seems to fail since PHP 8?
~~~
There was 1 failure:

1) BigBlueButton\Http\Transport\CurlTransportTest::testRequestWithCookie
session ID is OK
Failed asserting that null is identical to 'Monkey'.

/home/VERTRIEB/felix.jacobi/git/lib-upstream/bigbluebutton-api-php/tests/integration/Http/Transport/CurlTransportTest.php:129

~~~~

I will take a look as soon as possible. Our test HTTP server seems to do not send the cookie anymore.

### PR DESCRIPTION
**Pull request by FelixJacobi**
It seems that the format of the cookie jar of cURL cookie jar changed and so the regular expression no longer matches correctly. Good opportunity to get rid of the temporary file approach and remove almost all environment dependencies (here: writable file system).

This is a bigger change, but luckily we have integration tests here.

### CODE REVIEW

**Review by sualko — APPROVED** [review]
Code looks cleaner and integration tests are successful, so :+1: from my side.

**Comment by sualko** [comment]
can we merge this?

**Comment by SamuelWei** [comment]
Is there a test for getHeadersAndContentFromCurlHandle ?

**Comment by FelixJacobi** [comment]
Hm, to make Coveralls happy we must run `CurlTransportTest` in workflows, I guess. This should not be a problem. I would split the integration suite into integration (for `CurlTransport`, to make clear it isn't a real unit test due to environment dependencies) and functional (for the tests against real BBB).

**Comment by FelixJacobi** [comment]
> Hm, to make Coveralls happy we must run `CurlTransportTest` in workflows, I guess. This should not be a problem. I would split the integration suite into integration (for `CurlTransport`, to make clear it isn't a real unit test due to environment dependencies) and functional (for the tests against real BBB).

See  #90. Will rebase this PR. Coveralls should be fixed then.

**Pull request merged**
