### PR TITLE
Fix tests

### LINKED ISSUE #7: Tests
Provided tests are integration tests and no unit tests. Travis fails, because the test service is probably outdated (provides only API version 0.9). We probably need some kind of dependency injection to create real unit tests.

### PR DESCRIPTION
**Pull request by sualko**
fix #7

fix https://github.com/bigbluebutton/bigbluebutton-api-php/pull/79
fix https://github.com/bigbluebutton/bigbluebutton-api-php/pull/68
fix https://github.com/bigbluebutton/bigbluebutton-api-php/issues/69

### CODE REVIEW

**Comment by sualko** [comment]
> i think we want to support test with php7.4 version as well currently not working on php7.4

Yea, but that should be another pr. As a first step we should fix the tests, update travis and than upgrade all dependencies.

**Comment by sualko** [comment]
> The meta-parameter has no documented functionality, it is just an example of a custom meta-parameter that could be retrieved via the api.

That's right, but it doesn't hurt to test it anyway and I guess it's also no showstopper. So please approve this pr, so that we can continue with other stuff.

**Comment by SamuelWei** [comment]
I think there is a setRecordingReadyCallbackUrl function as well

**Comment by sualko** [comment]
The changes are in the `fix-tests` branch on this fork. So feel free to add more fixes to it.

**Pull request merged**
